@echo off
chcp 65001 >nul
setlocal
cd /d "%~dp0\.."

rem NOTE: keep this file ASCII-only. Non-ASCII text in a .bat file gets mangled
rem by cmd.exe when the file is UTF-8 but the console codepage is GBK, which
rem shatters lines into stray fragments like 'd_iscc' is not recognized.

echo ========================================
echo  NanoGhost - Build Windows Installer
echo ========================================
echo.

if /i "%~1"=="rebuild" goto :rebuild

if not exist "dist\NanoGhost\NanoGhost.exe" (
    echo [INFO] dist\NanoGhost\NanoGhost.exe not found, running PyInstaller first...
    echo.
    goto :rebuild
)
goto :find_iscc

:rebuild
echo [1/2] Building with PyInstaller...
call venv\Scripts\activate.bat
rem .env.example is generated by scanning os.getenv() in the source and is
rem bundled into the package, so it must be refreshed before every build.
python scripts\generate_env_template.py
if errorlevel 1 (
    echo.
    echo [ERROR] Failed to generate .env.example
    echo.
    pause
    exit /b 1
)
pyinstaller build.spec -y
if errorlevel 1 (
    echo.
    echo [ERROR] PyInstaller build failed.
    echo.
    pause
    exit /b 1
)
echo.

:find_iscc
set "PF86=%ProgramFiles(x86)%"
set "PF=%ProgramFiles%"
set "ISCC="
if exist "%LOCALAPPDATA%\Programs\Inno Setup 6\ISCC.exe" set "ISCC=%LOCALAPPDATA%\Programs\Inno Setup 6\ISCC.exe"
if not defined ISCC if exist "%PF86%\Inno Setup 6\ISCC.exe" set "ISCC=%PF86%\Inno Setup 6\ISCC.exe"
if not defined ISCC if exist "%PF%\Inno Setup 6\ISCC.exe" set "ISCC=%PF%\Inno Setup 6\ISCC.exe"

if not defined ISCC (
    echo [ERROR] ISCC.exe not found. Install Inno Setup first:
    echo         winget install JRSoftware.InnoSetup
    echo.
    pause
    exit /b 1
)

echo [2/2] Compiling installer...
echo        compiler: %ISCC%
echo.

"%ISCC%" "scripts\installer.iss"
if errorlevel 1 (
    echo.
    echo [ERROR] Installer compilation failed, see ISCC output above.
    echo.
    pause
    exit /b 1
)

echo.
echo ========================================
echo  Build Complete
echo ========================================
echo.
for %%F in ("dist\installer\*.exe") do echo   %%~nxF  (%%~zF bytes)
echo.
echo Output: dist\installer\
echo Copy that exe to the target machine and run it. No Python needed there.
echo.
pause
